[admin]
email = "gelectra@gitam.edu"
password = "123"
fullname = "gelectra admin"

[db]
host = "localhost"
user = "postgres"
password = "postgres"
dbname = "gelectra"
port = 5432


[auth]
jwt_secret = "sfdjksfkjslkdfjskldfjlskdjfklsdjfklsdj"
