[admin]
username = "gelectra@gitam.edu"
password = "123"

[db]
host = "localhost"
user = "postgres"
password = "postgres"
dbname = "gelectra"
port = 5432


[auth]
jwt_secret = "sfdjksfkjslkdfjskldfjlskdjfklsdjfklsdj"
